### ISSUE TITLE
Add: Radio Pitchoun

### ISSUE THREAD

**Issue by azgaresncf** [BellezaEmporium/IPRD#28]
### Radio name (required)

Radio Pitchoun

### Spoken language (required)

fra

### Genre

Children's

### Stream URL (required)

https://webradio.tvradio-pitchoun.fr:8443/radiopitchoun.aac

### Specific clause

Geo-blocked

**Comment by BellezaEmporium** [comment]
LGTM, adding it to fr.m3u. Thank you.
